"""Stable, explicit contract surface for Noetrium downstream authors.

Submodules remain available for discoverability; this package re-exports only
the names intentionally declared by each public contract family.
"""

from .agent import (
    AgentIdentity,
    AgentImplementation,
    AgentSession,
    AgentSnapshot,
    AgentTurnRequest,
    AgentTurnResult,
    AgentActionExecutorPort,
    AgentActionSequence,
    AgentActionStep,
    AgentActionSummary,
    AgentCognitionError,
    AgentCompletionPort,
    AgentDiagnosticsPort,
    AgentEvidencePort,
    AgentGoal,
    AgentLoopCheckpoint,
    AgentLoopResult,
    AgentLoopTerminationReason,
    AgentMemoryContext,
    AgentMemoryPort,
    AgentModeDecision,
    AgentModeDisposition,
    AgentObservation,
    AgentObservationPort,
    AgentPlannerPort,
    AgentPlanningRequest,
    AgentProgressPort,
    AgentReactiveModePort,
    AgentReceiptCheckpoint,
    AgentSafetyDecision,
    AgentSafetyDisposition,
    AgentSafetySupervisorPort,
    AgentSkillCatalogPort,
    AgentSkillDescription,
    AgentSkillLibraryPort,
    AgentSkillRecord,
    AgentSkillSelection,
    AgentStepReceipt,
    action_summary_payload,
)
from .json import (
    CanonicalDecodingError,
    CanonicalDecodingFailureKind,
    CanonicalEncodingError,
    DigestValidationError,
    JsonDocument,
    JsonInput,
    JsonMutableValue,
    JsonObject,
    JsonScalar,
    JsonValue,
    Sha256Digest,
    canonical_bytes,
    canonical_digest,
    canonical_text,
    freeze_json,
    require_sha256,
    strict_finite_json_bytes,
    strict_finite_json_digest,
    strict_finite_json_text,
    strict_json_loads,
    thaw_json,
)
from .research import (
    CompiledResearchPlan,
    ExperimentRunner,
    ExperimentRunnerPort,
    ResearchBindingContribution,
    ResearchMethodHost,
    ResearchMethodHostPort,
    ResearchPlanDiff,
    ResearchStudyDefinition,
    RunControlPort,
    compile_research_plan,
    diff_research_plans,
    resolve_research_requirements,
)
from .project import (
    PROJECT_MANIFEST_SCHEMA,
    ProjectIdentity,
    ProjectManifest,
    ProjectManifestDecodeError,
    ProjectSpec,
    ProjectToolProvenance,
    decode_project_manifest_bytes,
    decode_project_manifest_document,
    encode_project_manifest,
    project_manifest_document,
)
from .participant import (
    AgentProjectDefinition,
    MethodProjectDefinition,
    ParticipantBindingDiagnostic,
    ParticipantBindingDiagnosticCode,
    ParticipantBindingDiagnosticSeverity,
    ParticipantProjectBindingError,
    ParticipantProviderProfile,
    ParticipantRequirement,
    ParticipantRequirementContribution,
    ProjectParticipantBinding,
    ProjectParticipantProviderPort,
)
from .model import (
    ModelBindingDiagnostic,
    ModelBindingDiagnosticCode,
    ModelBindingDiagnosticSeverity,
    ModelCapabilityRequirement,
    ModelProjectBindingError,
    ModelProjectDefinition,
    ModelProviderProfile,
    ProjectModelBinding,
    ProjectModelClientPort,
    ProjectModelProviderPort,
    ProjectModelRequest,
    ProjectModelResponse,
)
from .environment import (
    ActionRequest,
    ActionResult,
    EnvironmentCapability,
    EnvironmentCapabilityUnsupported,
    EnvironmentDiagnosticsPort,
    EnvironmentIdentity,
    EnvironmentImplementation,
    EnvironmentProviderCapabilities,
    EnvironmentProviderPort,
    EnvironmentSession,
    EnvironmentSessionDiagnostics,
    EnvironmentSessionServices,
    Observation,
)

__all__ = [
    "AgentIdentity", "AgentImplementation", "AgentSession", "AgentSnapshot",
    "AgentTurnRequest", "AgentTurnResult",
    "AgentActionExecutorPort", "AgentActionSequence", "AgentActionStep",
    "AgentActionSummary", "AgentCognitionError", "AgentCompletionPort",
    "AgentDiagnosticsPort", "AgentEvidencePort", "AgentGoal",
    "AgentLoopCheckpoint", "AgentLoopResult", "AgentLoopTerminationReason",
    "AgentMemoryContext", "AgentMemoryPort", "AgentModeDecision",
    "AgentModeDisposition", "AgentObservation", "AgentObservationPort",
    "AgentPlannerPort", "AgentPlanningRequest", "AgentProgressPort",
    "AgentReactiveModePort", "AgentReceiptCheckpoint", "AgentSafetyDecision",
    "AgentSafetyDisposition", "AgentSafetySupervisorPort",
    "AgentSkillCatalogPort", "AgentSkillDescription", "AgentSkillLibraryPort",
    "AgentSkillRecord", "AgentSkillSelection", "AgentStepReceipt",
    "action_summary_payload",
    "CanonicalDecodingError", "CanonicalDecodingFailureKind",
    "CanonicalEncodingError", "DigestValidationError", "JsonDocument",
    "JsonInput", "JsonMutableValue", "JsonObject", "JsonScalar", "JsonValue",
    "Sha256Digest", "canonical_bytes", "canonical_digest", "canonical_text",
    "freeze_json", "require_sha256", "strict_finite_json_bytes",
    "strict_finite_json_digest", "strict_finite_json_text", "strict_json_loads",
    "thaw_json",
    "CompiledResearchPlan", "ExperimentRunner", "ExperimentRunnerPort",
    "ResearchBindingContribution", "ResearchMethodHost", "ResearchMethodHostPort",
    "ResearchPlanDiff", "ResearchStudyDefinition", "RunControlPort",
    "compile_research_plan", "diff_research_plans", "resolve_research_requirements",
    "PROJECT_MANIFEST_SCHEMA", "ProjectIdentity", "ProjectManifest",
    "ProjectManifestDecodeError", "ProjectSpec", "ProjectToolProvenance",
    "decode_project_manifest_bytes", "decode_project_manifest_document",
    "encode_project_manifest", "project_manifest_document",
    "AgentProjectDefinition", "MethodProjectDefinition",
    "ParticipantBindingDiagnostic", "ParticipantBindingDiagnosticCode",
    "ParticipantBindingDiagnosticSeverity", "ParticipantProjectBindingError",
    "ParticipantProviderProfile", "ParticipantRequirement",
    "ParticipantRequirementContribution", "ProjectParticipantBinding",
    "ProjectParticipantProviderPort",
    "ModelBindingDiagnostic", "ModelBindingDiagnosticCode",
    "ModelBindingDiagnosticSeverity", "ModelCapabilityRequirement",
    "ModelProjectBindingError", "ModelProjectDefinition", "ModelProviderProfile",
    "ProjectModelBinding", "ProjectModelClientPort", "ProjectModelProviderPort",
    "ProjectModelRequest", "ProjectModelResponse",
    "ActionRequest", "ActionResult", "EnvironmentCapability",
    "EnvironmentCapabilityUnsupported", "EnvironmentDiagnosticsPort",
    "EnvironmentIdentity", "EnvironmentImplementation",
    "EnvironmentProviderCapabilities", "EnvironmentProviderPort",
    "EnvironmentSession", "EnvironmentSessionDiagnostics",
    "EnvironmentSessionServices", "Observation",
]
