"""Research lifecycle contracts for downstream project authors."""

from noetrium_platform.research.experimentation.api import (
    CompiledResearchPlan,
    ExperimentRunner,
    ExperimentRunnerPort,
    ResearchBindingContribution,
    ResearchMethodHost,
    ResearchMethodHostPort,
    ResearchPlanDiff,
    ResearchStudyDefinition,
    compile_research_plan,
    diff_research_plans,
    resolve_research_requirements,
)
from noetrium_platform.research.experimentation.run.api import (
    RunArtifactKind,
    RunArtifactSnapshotReceipt,
)
from noetrium_platform.research.experimentation.study.api import (
    BoundStudyUnitExecutionPort,
    BoundStudyVariantExecutionPort,
    ExperimentPlan,
    StudyAssignment,
    StudyConcurrencyPolicy,
    StudyExecutionUnit,
    StudyMatrixExecutionReport,
    StudyMetricAggregate,
    StudyMetricObservation,
    StudyProtocol,
    StudyVariantExecutionPort,
    StudyVariantSpec,
    VariantBinding,
    VariantKind,
    MeasurementRecord,
    MeasurementValue,
    MeasurementValueKind,
    TrialMatrixExecutionReport,
)
from noetrium_platform.research.experimentation.study.runtime import (
    BasicStudyMetricAggregator,
    DeterministicStudyAssignment,
    StudyMatrixExecutor,
)
from noetrium_platform.research.experimentation.workbench import (
    AggregationFunction,
    AggregationSpec,
    BaselineRegistryPort,
    BaselineSpec,
    CsvTableReader,
    DataColumn,
    DataTable,
    EvaluationContext,
    EvaluationStage,
    FigureCell,
    FigureKind,
    FigurePoint,
    FigureSeries,
    FigureSpec,
    FigureStyle,
    GroupComparison,
    InferenceResult,
    JsonlTableReader,
    MetricSummary,
    MeasurementRecordTableAdapter, StudyObservationTableAdapter,
    MissingValuePolicy,
    PairedComparison,
    RenderedResearchPackage,
    ResearchEvaluation,
    ResearchFigureFactory,
    ResearchLifecycle,
    ResearchReport,
    ScientificStatistics,
    SplitStrategy,
    StandardTableRenderer,
    SvgFigureRenderer,
    TablePipeline,
)
from noetrium_platform.research.experimentation.run.control.api import (
    RunControlAction,
    RunControlActionFailure,
    RunControlConflict,
    RunControlError,
    RunControlEventReceipt,
    RunControlIntegrityError,
    RunControlNotFound,
    RunControlPhase,
    RunControlPort,
    RunControlReceipt,
    RunControlReceiptReference,
    RunControlRecordKind,
    RunControlRequest,
    RunControlStaleGeneration,
    RunControlTarget,
    RunControlTransitionOutcome,
    RunEvidenceValidity,
    RunExecutionOutcome,
    RunOutcomeProjection,
    RunScientificValidity,
    RunTaskOutcome,
)
from noetrium_platform.research.experimentation.run.manifest.api.evidence import (
    DerivedEvidenceArtifact,
    EvidenceBundleManifest,
    EvidenceBundleReceipt,
    EvidenceBundleStatus,
    EvidenceStreamDescriptor,
)

__all__ = [
    "CompiledResearchPlan", "ExperimentRunner", "ExperimentRunnerPort",
    "ResearchBindingContribution", "ResearchMethodHost", "ResearchMethodHostPort",
    "ResearchPlanDiff", "ResearchStudyDefinition", "compile_research_plan",
    "diff_research_plans", "resolve_research_requirements",
    "RunArtifactKind", "RunArtifactSnapshotReceipt", "RunControlAction",
    "RunControlActionFailure", "RunControlConflict", "RunControlError",
    "RunControlEventReceipt", "RunControlIntegrityError", "RunControlNotFound",
    "RunControlPhase", "RunControlPort", "RunControlReceipt",
    "RunControlReceiptReference", "RunControlRecordKind", "RunControlRequest",
    "RunControlStaleGeneration", "RunControlTarget", "RunControlTransitionOutcome",
    "RunEvidenceValidity", "RunExecutionOutcome", "RunOutcomeProjection",
    "RunScientificValidity", "RunTaskOutcome", "DerivedEvidenceArtifact",
    "EvidenceBundleManifest", "EvidenceBundleReceipt", "EvidenceBundleStatus",
    "EvidenceStreamDescriptor",
    "BoundStudyUnitExecutionPort", "BoundStudyVariantExecutionPort", "ExperimentPlan",
    "StudyAssignment", "StudyConcurrencyPolicy", "StudyExecutionUnit",
    "StudyMatrixExecutionReport", "StudyMetricAggregate", "StudyMetricObservation",
    "StudyProtocol", "StudyVariantExecutionPort", "StudyVariantSpec", "VariantBinding",
    "VariantKind", "MeasurementRecord", "MeasurementValue", "MeasurementValueKind",
    "TrialMatrixExecutionReport", "BasicStudyMetricAggregator", "DeterministicStudyAssignment",
    "StudyMatrixExecutor",
    "AggregationFunction", "AggregationSpec", "BaselineRegistryPort", "BaselineSpec", "CsvTableReader", "DataColumn", "DataTable", "EvaluationContext", "EvaluationStage", "FigureCell", "FigureKind", "FigurePoint",
    "FigureSeries", "FigureSpec", "FigureStyle", "GroupComparison", "InferenceResult", "JsonlTableReader",
    "MetricSummary", "MeasurementRecordTableAdapter", "MissingValuePolicy",
    "PairedComparison", "RenderedResearchPackage", "ResearchEvaluation", "ResearchFigureFactory",
    "ResearchLifecycle", "ResearchReport", "StudyObservationTableAdapter",
    "ScientificStatistics", "SplitStrategy", "StandardTableRenderer", "SvgFigureRenderer",
    "TablePipeline",
]
