from __future__ import annotations
from typing import Protocol, runtime_checkable
from .contracts import SystemDescriptor

@runtime_checkable
class SystemRegistryPort(Protocol):
    def register(self, descriptor: SystemDescriptor) -> None: ...
    def get(self, key: str) -> SystemDescriptor: ...
    def contains(self, key: str) -> bool: ...
    def list(self) -> tuple[SystemDescriptor, ...]: ...
    def children(self, key: str) -> tuple[SystemDescriptor, ...]: ...
    def owner_for_module(self, module: str) -> SystemDescriptor | None: ...

__all__=["SystemRegistryPort"]
