"""Public typed architecture/composition contracts for advanced consumers."""

from .capability_composition import (
    AmbiguousCapabilityProvider,
    BindingEdge,
    BindingPlan,
    CapabilityBindingError,
    CapabilityCompositionPlannerPort,
    CapabilityDependencyCycle,
    CapabilityInterfaceMismatch,
    CapabilityKey,
    CapabilityOffer,
    CapabilityRequirement,
    CompositionContract,
    CompositionContractError,
    CompositionIdentity,
    CompositionSubject,
    CompositionSubjectKind,
    CompositionTopologyError,
    MissingCapabilityProvider,
    ProviderSelection,
    RequirementAddress,
    RequirementCardinality,
    interface_contract_digest,
)

from .semantic_boundary import (
    SemanticBoundaryClaim,
    SemanticBoundaryClaimError,
    SemanticBoundaryClassification,
    SemanticBoundaryEvidence,
    SemanticStateAuthorityKind,
    validate_semantic_boundary_claim,
)

__all__ = [
    "AmbiguousCapabilityProvider",
    "BindingEdge",
    "BindingPlan",
    "CapabilityBindingError",
    "CapabilityCompositionPlannerPort",
    "CapabilityDependencyCycle",
    "CapabilityInterfaceMismatch",
    "CapabilityKey",
    "CapabilityOffer",
    "CapabilityRequirement",
    "CompositionContract",
    "CompositionContractError",
    "CompositionIdentity",
    "CompositionSubject",
    "CompositionSubjectKind",
    "CompositionTopologyError",
    "MissingCapabilityProvider",
    "ProviderSelection",
    "RequirementAddress",
    "RequirementCardinality",
    "interface_contract_digest",
    "SemanticBoundaryClaim",
    "SemanticBoundaryClaimError",
    "SemanticBoundaryClassification",
    "SemanticBoundaryEvidence",
    "SemanticStateAuthorityKind",
    "validate_semantic_boundary_claim",
]
